Only pass decoded strings logging
Python (2.7) has a requirement to only pass unicode string to stream io
modules. That causes non-fatal type error but error print is very
verbose masking useful debug prints from application side.

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 872, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file unattended-upgrade, line 402

Signed-off-by: Pauli Nieminen <suokkos@gmail.com>